version: 2 # use CircleCI 2.0
# https://circleci.com/docs/2.0/language-php/ adopted from Laravel example
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    docker: # run the steps with Docker
      - image: circleci/php:5.6-node-browsers # ...with this image as the primary container; this is where all `steps` will run
    working_directory: ~/app # directory where steps will run
    steps: # a set of executable commands
      - checkout # special step to check out source code to working directory
      - run: sudo docker-php-ext-install zip
      - run:
          name: "PHP Syntax Check. Breaks on first found invalid file to reduce check time."
          command: |
            find . -name '*.php' -print0 | xargs -n 1 -0 php -l